// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: workshopParser.proto

package workshopParser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkshopParser_ParseWorkshopItem_FullMethodName = "/workshopParser.workshopParser/ParseWorkshopItem"
)

// WorkshopParserClient is the client API for WorkshopParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkshopParserClient interface {
	ParseWorkshopItem(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type workshopParserClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkshopParserClient(cc grpc.ClientConnInterface) WorkshopParserClient {
	return &workshopParserClient{cc}
}

func (c *workshopParserClient) ParseWorkshopItem(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, WorkshopParser_ParseWorkshopItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkshopParserServer is the server API for WorkshopParser service.
// All implementations must embed UnimplementedWorkshopParserServer
// for forward compatibility
type WorkshopParserServer interface {
	ParseWorkshopItem(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedWorkshopParserServer()
}

// UnimplementedWorkshopParserServer must be embedded to have forward compatible implementations.
type UnimplementedWorkshopParserServer struct {
}

func (UnimplementedWorkshopParserServer) ParseWorkshopItem(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseWorkshopItem not implemented")
}
func (UnimplementedWorkshopParserServer) mustEmbedUnimplementedWorkshopParserServer() {}

// UnsafeWorkshopParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkshopParserServer will
// result in compilation errors.
type UnsafeWorkshopParserServer interface {
	mustEmbedUnimplementedWorkshopParserServer()
}

func RegisterWorkshopParserServer(s grpc.ServiceRegistrar, srv WorkshopParserServer) {
	s.RegisterService(&WorkshopParser_ServiceDesc, srv)
}

func _WorkshopParser_ParseWorkshopItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkshopParserServer).ParseWorkshopItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkshopParser_ParseWorkshopItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkshopParserServer).ParseWorkshopItem(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkshopParser_ServiceDesc is the grpc.ServiceDesc for WorkshopParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkshopParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workshopParser.workshopParser",
	HandlerType: (*WorkshopParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseWorkshopItem",
			Handler:    _WorkshopParser_ParseWorkshopItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workshopParser.proto",
}
